spring:
  application:
    name: CurrencyService
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterWrite=1h

app:
  client:
    url: https://www.cbr.ru/scripts/XML_daily.asp

resilience4j:
  circuitbreaker:
    instances:
      external-system:
        slidingWindowSize: 10
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 10s
        minimumNumberOfCalls: 3
