spring:
  application:
    name: KudaGo

base-config:
  kuda-go-url: https://kudago.com/public-api/v1.4/
  currency-url: http://localhost:8080/api/v1/currencies

multithreading:
  fixed-pool-size: 20
  scheduled-pool-size: 10
  period-in-seconds: 5
  delay-in-seconds: 3
  max-num-of-threads: 3

server:
  port: 8081