name: Build Currency service with tests

on:
  pull_request:
    branches:
      - no

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: gradle

      # Grant permission to execute the gradlew script
      - name: Grant execute permission for gradlew
        working-directory: ./CurrencyService
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        working-directory: ./CurrencyService
        run: ./gradlew build

