name: Build KudaGo with tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - fj_2024_lesson_8

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    permissions:
      contents: read
      pull-requests: write

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: kudago
          POSTGRES_USER: kudago
          POSTGRES_PASSWORD: kudago
        ports:
          - 5555:5432
        options: >-
          --health-cmd "pg_isready -U kudago"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: gradle

      # Grant permission to execute the gradlew script
      - name: Grant execute permission for gradlew
        working-directory: ./KudaGo
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        working-directory: ./KudaGo
        run: ./gradlew build

      - id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        if: ( github.event_name != 'workflow_dispatch' )
        with:
          paths: ${{ github.workspace }}/**/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 70
          min-coverage-changed-files: 70
          title: Code Coverage
          update-comment: true